[package]
name = "prepper_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
leptos = "0.2.3"
prepper_core = { version = "0.1.0", path = "../prepper_core" }
web-sys = "0.3.61"
